# FM Net Configuration
model_name: "fm_net"
network_type: "FMnet"
flow_type: "GaussFlowMatching_OT"  # No TTF logging
use_ttf_logging: false

# Training parameters
training:
  batch_size: 8192
  epochs: 5
  lr: 0.0001
  device: "cuda"

# Model parameters
model:
  hidden_dim: 64  # FMnet uses 'h' parameter
  input_dim: 2

# TTF parameters (not used for this model)
ttf:
  log_interval: 50

# Data parameters
data:
  data_file: "data/ST2.npy"
  num_samples: 100000
  train_ratio: 0.8  # 80% train, 20% test

# Output parameters
output:
  output_dir: "outputs"