# Flow Matching with X0 Heavy-Tail transformation
model_name: "fm_x0_ht"
network_type: "FMnet"
flow_type: "FlowMatchingX0HT"  # Special X0 transformation
use_ttf_logging: false

# Training parameters
training:
  batch_size: 8192
  epochs: 500
  lr: 0.0001
  device: "cuda"
  weight_decay: 0.001  # Special for this model

# Model parameters
model:
  hidden_dim: 64
  input_dim: 2

# TTF parameters
ttf:
  log_interval: 50

# Data parameters
data:
  data_file: "data/ST2.npy"
  num_samples: 100000
  train_ratio: 0.8  # 80% train, 20% test

# Output parameters
output:
  output_dir: "outputs"